mDL Presentment Flow: Unification of Presentment Prompts (#647)
* mDL Presentment Flow: Unification of Presentment Prompts

Created PresentmentFlow to start a Presentment Flow for all document
requests and obtain the response bytes with all the Documents from
successful Presentment Flows (once all the prompts succeed).
An exception is thrown otherwise.

Refactored PresentationActivity in Wallet to be a transparent Activity
and removed all Compose components. Once the device listener has
the device request bytes it immediately uses PresentmentFlow to start
showing the Presentment Prompts and receive the response bytes to
send back to the device.

Test: all unit tests ran and passed.
Test: manual mDL Presentment via NFC and QR engagement between Wallet
and AppVerifier.
Test: Requesting multiple docRequests via Request mDL + micov with linkage — works for only the Mdoc type since I couldnt find a way to add a micov docType to Wallet.

Signed-off-by: dritan-x <dritan.xhabija@gmail.com>

* Updates to Presentment Flow

- Showing the Presentment Flow is now done via showPresentmentFlow()
- Wallet PresentationActivity now parses the device request bytes and
  calls showPresentmentFlow() with each parsed DocumentRequest
- Removed one of the PassphraseEntryFields and updated its references
- Changed the access modifiers to public for the ConsentPrompt and
  PassphrasePrompt Dialog Fragments, that addresses
    IllegalStateException: Fragment must be a public static class to be
    properly recreated from instance state.

test: manual presentment between Wallet and AppVerifier
test: all unit tests pass (419)
Signed-off-by: dritan-x <dritan.xhabija@gmail.com>

* Updates to Presentment Flow

Test: all unit tests pass
Test: successful mDL Presentment Flow between Wallet and AppVerifier
Signed-off-by: dritan-x <dritan.xhabija@gmail.com>

---------

Signed-off-by: dritan-x <dritan.xhabija@gmail.com>