Updates to Presentment Flow
- Showing the Presentment Flow is now done via showPresentmentFlow()
- Wallet PresentationActivity now parses the device request bytes and
  calls showPresentmentFlow() with each parsed DocumentRequest
- Removed one of the PassphraseEntryFields and updated its references
- Changed the access modifiers to public for the ConsentPrompt and
  PassphrasePrompt Dialog Fragments, that addresses
    IllegalStateException: Fragment must be a public static class to be
    properly recreated from instance state.

test: manual presentment between Wallet and AppVerifier
test: all unit tests pass (419)
Signed-off-by: dritan-x <dritan.xhabija@gmail.com>